### ISSUE TITLE
Ansible Role to Provision a Jenkins Update Center Mirror

### ISSUE THREAD

**Issue by timblaktu** [wcm-io-devops/ansible-jenkins-plugins#10]
[In some comments [here](https://github.com/wcm-io-devops/ansible-jenkins-plugins/blob/4ea685d8290d27ff617a4a6b90b725ada50bfed2/defaults/main.yml#L48) and [here](https://github.com/wcm-io-devops/ansible-jenkins-plugins/issues/8#issuecomment-665454663) you suggest to prop up a local mirror to speed up this role. I am also interested in this for stability reasons - I regularly get connection time out errors downloading either the .war from https://pkg.jenkins.io/debian-stable/binary or plugins from the various sites. This issue is to: 

1. Ask "is there any existing role in wcm-io-devops I could use as a starting point for setting up this mirror?" I found the jenkins update site generator project](https://github.com/jenkins-infra/update-center2) and [some](https://github.com/ikedam/backend-update-center2/wiki/How-to-create-your-own-Jenkins-Update-Center) [forks](https://github.com/LinuxSuRen/update-center2) which provide some guidance on setting up a private mirror - is this the approach you are using to create update site mirrors?
2. Would you be interested in adding a role to wcm-io-devops for this purpose, if I created and submitted one from a personal repo?

Thanks for your time.

**Comment by tobias-richter** [comment]
Hi @timblaktu just noticed this issue and that nobody has answered jet.
Regarding your questions.

> is there any existing role in wcm-io-devops I could use as a starting point for setting up this mirror?

No there is no role available and there is currently no plan to do so.
I have also checked the update site generator and the effort was not worth it until now.
What we are doing is mirroring the binaries to an internal server which then can be used as download site for the `jenkins_plugin`. So we are speeding up response and transfer times, but we are still using the normal update-site for update check and installing plugins manually.

What we are doing is simple:
rsync from an existing update-site which is located near to our infrastructure via cron-job

```
#!/bin/bash


echo "####################################################################################################################" | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')
echo "sync debian-stable from 'ftp.halifax.rwth-aachen.de/jenkins' to '/var/www/jenkins-update-site/debian-stable'" | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')
echo "####################################################################################################################" | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')
rsync --bwlimit=5000 -rltDv --delete rsync://ftp.halifax.rwth-aachen.de/jenkins/debian-stable/ '/var/www/jenkins-update-site/debian-stable' | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')

echo "####################################################################################################################" | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')
echo "sync updates from 'ftp.halifax.rwth-aachen.de/jenkins'" to '/var/www/jenkins-update-site/updates' | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')
echo "####################################################################################################################" | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')
rsync --bwlimit=5000 -rltDv --delete --exclude download rsync://ftp.halifax.rwth-aachen.de/jenkins/updates/ '/var/www/jenkins-update-site/updates' | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')

echo "####################################################################################################################" | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')
echo "sync plugins from 'ftp.halifax.rwth-aachen.de/jenkins'" to '/var/www/jenkins-update-site/plugins' | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')
echo "####################################################################################################################" | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')
rsync --bwlimit=5000 -rltDv --delete rsync://ftp.halifax.rwth-aachen.de/jenkins/plugins/ '/var/www/jenkins-update-site/plugins' | tee >(ts "%Y-%m-%d %H:%M:%S" >> '/var/log/jenkins-update-site/sync.log')

chown -R www-data:www-data '/var/www/jenkins-update-site'
```

We are then simply serving the content of "/var/www/jenkins-update-site/" via apache/httpd

> Would you be interested in adding a role to wcm-io-devops for this purpose, if I created and submitted one from a personal repo?

This is something we can talk about :)

**Comment by tobias-richter** [comment]
Feel free to open again if required.
