### ISSUE TITLE
missing wcm-io-devops prefix to ansible-jenkins-plugins role name

### ISSUE THREAD

**Issue by timblaktu** [wcm-io-devops/ansible-jenkins-plugins#9]
I have installed 3 of your ansible roles using:

`ansible-galaxy role install -r requirements-jenkins.yml`

where `requirements-jenkins.yml` contains:

```
- src: https://github.com/wcm-io-devops/ansible-jenkins-plugins
  version: 1.4.0
- src: https://github.com/wcm-io-devops/ansible-jenkins-facts
  version: 1.3.0
- src: https://github.com/wcm-io-devops/ansible-jenkins-service
  version: 1.2.1
```

and when I list the installed roles, I see that ansible-jenkins-plugins doesn't include the "wcm-io-devops." prefix like the others:

```
[tblack-stretch]tblack/src/cm/ansible > ansible-galaxy list
# /etc/ansible/roles
- ansible-jenkins-service, 1.2.1
- wcm_io_devops.jenkins_facts, 1.2.2
- ansible-jenkins-plugins, 1.4.0
- wcm_io_devops.jenkins_service, 1.2.1
- ansible-jenkins-facts, 1.3.0
```

Therefore when I follow the pattern in your example playbook by invoking this role using:

```
.
.
.
  roles:
    - role: wcm_io_devops.jenkins_plugins
```

I get this error running my playbook:

```
ERROR! the role 'wcm_io_devops.jenkins_plugins' was not found in /home/tblack/src/cm/ansible/roles:/etc/ansible/roles:/home/tblack/.ansible/collections/ansible_collections/pulp/pulp_installer/roles:/home/tblack/src/cm/ansible

The error appears to be in '/home/tblack/src/cm/ansible/jenkins.yml': line 321, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: wcm_io_devops.jenkins_plugins
      ^ here
```

I suspected the problem might be related to the fact that I'm explicitly including the dependencies here, so I change my requirements file to exclude them, and only include the ansible-jenkins-plugins role I need:

```
- src: https://github.com/wcm-io-devops/ansible-jenkins-plugins                                                                                    version: 1.4.0
```

and I get no change:

```
[tblack-stretch]tblack/src/cm/ansible > ansible-galaxy role install -r requirements-jenkins.yml
- ansible-jenkins-plugins (1.4.0) is already installed, skipping.
[tblack-stretch]tblack/src/cm/ansible > ansible-galaxy list
# /etc/ansible/roles
- ansible-jenkins-service, 1.2.1
- wcm_io_devops.jenkins_facts, 1.2.2
- ansible-jenkins-plugins, 1.4.0
- wcm_io_devops.jenkins_service, 1.2.1
- ansible-jenkins-facts, 1.3.0
```

Expected Result:
That when I install the roles from these requirements files, that I would get a role named "wcm_io_devops.jenkins_plugins". 

For now, I have adjusted my playbook to use the role with the name it appears to have, like this:

```
    roles:                                                                                                                                             
    - role: ansible-jenkins-plugins
```

and I have worked around the error.

**Comment by tobias-richter** [comment]
@timblaktu this is a picnic :) (Problem in chair, not in computer). I suggest to refer to the ansible and ansible-galaxy documentation since you are not defining the galaxy requirements as they should be defined.

For example: https://galaxy.ansible.com/wcm_io_devops/jenkins_service

Your requirement is either

```
- name: wcm_io_devops.jenkins_service
  version: 1.2.1
```

Or, if you really want to define the GIT repo (which is only necessary when you want to specify a specific commit):

```
- name: wcm_io_devops.jenkins_service
  src: https://github.com/wcm-io-devops/ansible-jenkins-plugins.git
  scm: git
  version: 1.4.0
```

**Comment by timblaktu** [comment]
Sorry this one wasn't a picnic for me too! You're right; I had gotten used to specifying the git repo in my galaxy requirements files. Generally, the name isn't required, and it defaults to the repo name. But your point is well taken, I will start using explicit role names as per the galaxy role page indicates. Indeed I'm able to include your roles now. Thanks for your help!
